name: Daily HL Portfolio Run

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 07:00 UTC
  workflow_dispatch:      # Allows manual runs too

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      LC_ALL: en_GB.UTF-8
      LANG: en_GB.UTF-8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch private data repo
        env:
          GH_PAT: ${{ secrets.DATA_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_PAT}@github.com/mastershivam/HL_Daily_Prices_Data.git
          cp units.csv units.csv
          cp urls.csv urls.csv

      - name: Run script
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_TO: ${{ secrets.EMAIL_RECIPIENTS}}
        run: python main.py
